name: PR Checks

on:
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  call-basic-checks:
    name: Run Organization Basic PR Quality Checks
    uses: sessatakuma/org-workflows/.github/workflows/basic.yml@main
    secrets:
      CHECKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
